# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
# use your API Key from https://apps.twitter.com/
development:
  secret_key_base: 000000063d24de5649e0d745cc5ff8061b7d0c550a6d606a11ca2289d7ee318e76317c1454e417c7a0a6200827356bcc09651e15061ea8ecc97b3ac4e98542
  twitter_api_key: 0000000jOhx3nnwgZs7nhcY5
  twitter_api_secret: 0000000uCs7VzqDXajoOqc6Y25hwYa0wpOD4Wzo4sL1elD

test:
  secret_key_base: 0000000f2b19bb8d616144bd92d2edc31656014f5310dc4070cde45ab9bcba880213b6dc8d4a56f441200d786598292892bae71efc0b3af58ed2f837fbb9b5fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
